export interface PresetCategory {
  id: string;
  label: string;
  russianLabel: string;
  icon: string;
  groupId: string;
  groupName: string;
  categoryId: number;
  typeId: number;
  categoryName: string;
  typeName: string;
  path: string[];
}

export interface PresetCategoryGroup {
  id: string;
  name: string;
  icon: string;
  categories: PresetCategory[];
}

export const PRESET_CATEGORIES: PresetCategory[] = [
  // 1. Mutfak & Pişirme Küçük Ev Aletleri
  {
    id: 'airfryer',
    label: 'Airfryer',
    russianLabel: 'Аэрогриль',
    icon: '🍟',
    groupId: 'kitchen-cooking',
    groupName: 'Mutfak & Pişirme Aletleri',
    categoryId: 17039629,
    typeId: 94726,
    categoryName: 'Buharlı pişirici, ekmek pişirici, aerogrill',
    typeName: 'Airfryer',
    path: ['Ev aletleri', 'Buharlı pişirici, ekmek pişirici, aerogrill', 'Airfryer'],
  },
  {
    id: 'kahve-makinesi',
    label: 'Otomatik Kahve Makinesi',
    russianLabel: 'Кофемашина',
    icon: '☕',
    groupId: 'kitchen-cooking',
    groupName: 'Mutfak & Pişirme Aletleri',
    categoryId: 17039628,
    typeId: 94971,
    categoryName: 'Kahve makineleri ve barista tipi kahve makineleri',
    typeName: 'Otomatik Kahve Makinesi',
    path: ['Ev aletleri', 'Kahve makineleri ve barista tipi kahve makineleri', 'Otomatik Kahve Makinesi'],
  },
  {
    id: 'meyve-sikacagi',
    label: 'Katı Meyve Sıkacağı',
    russianLabel: 'Соковыжималка',
    icon: '🍊',
    groupId: 'kitchen-cooking',
    groupName: 'Mutfak & Pişirme Aletleri',
    categoryId: 17039644,
    typeId: 94989,
    categoryName: 'Соковыжималки',
    typeName: 'Elektrikli meyve sıkacağı',
    path: ['Бытовая техника', 'Соковыжималки', 'Соковыжималка электрическая'],
  },
  {
    id: 'kettle',
    label: 'Kettle / Su Isıtıcısı',
    russianLabel: 'Электрочайник',
    icon: '🫖',
    groupId: 'kitchen-cooking',
    groupName: 'Mutfak & Pişirme Aletleri',
    categoryId: 17039631,
    typeId: 94968,
    categoryName: 'Elektrikli su ısıtıcıları ve termopotlar',
    typeName: 'Elektrikli su Isıtıcısı',
    path: ['Ev aletleri', 'Elektrikli su ısıtıcıları ve termopotlar', 'Elektrikli su Isıtıcısı'],
  },

  // 2. Gıda Hazırlama & Mikser/Robot
  {
    id: 'blender',
    label: 'Blender',
    russianLabel: 'Блендер',
    icon: '🥤',
    groupId: 'food-prep',
    groupName: 'Gıda Hazırlama & Mikserler',
    categoryId: 17039627,
    typeId: 94973,
    categoryName: 'Mikserler, blenderlar ve öğütücüler',
    typeName: 'Blender',
    path: ['Ev aletleri', 'Mikserler, blenderlar ve öğütücüler', 'Blender'],
  },
  {
    id: 'mikser',
    label: 'Mikser',
    russianLabel: 'Миксер',
    icon: '🥣',
    groupId: 'food-prep',
    groupName: 'Gıda Hazırlama & Mikserler',
    categoryId: 17039627,
    typeId: 94982,
    categoryName: 'Mikserler, blenderlar ve öğütücüler',
    typeName: 'Mutfak mikseri',
    path: ['Ev aletleri', 'Mikserler, blenderlar ve öğütücüler', 'Mutfak mikseri'],
  },
  {
    id: 'mutfak-robotu',
    label: 'Mutfak Robotu',
    russianLabel: 'Кухонный комбайн',
    icon: '🥗',
    groupId: 'food-prep',
    groupName: 'Gıda Hazırlama & Mikserler',
    categoryId: 17039627,
    typeId: 94979,
    categoryName: 'Mikserler, blenderlar ve öğütücüler',
    typeName: 'Çok amaçlı mutfak robotu',
    path: ['Ev aletleri', 'Mikserler, blenderlar ve öğütücüler', 'Çok amaçlı mutfak robotu'],
  },
  {
    id: 'mutfak-sefi',
    label: 'Mutfak Şefi (Planetary)',
    russianLabel: 'Кухонная машина',
    icon: '👨‍🍳',
    groupId: 'food-prep',
    groupName: 'Gıda Hazırlama & Mikserler',
    categoryId: 17039627,
    typeId: 970686722,
    categoryName: 'Mikserler, blenderlar ve öğütücüler',
    typeName: 'Mutfak şefi',
    path: ['Ev aletleri', 'Mikserler, blenderlar ve öğütücüler', 'Mutfak şefi'],
  },

  // 3. Ütüleme & Buhar Sistemleri
  {
    id: 'buhar-jeneratorlu-utu',
    label: 'Buhar Jeneratörlü Ütü',
    russianLabel: 'Парогенератор',
    icon: '💨',
    groupId: 'ironing-steam',
    groupName: 'Ütü & Buhar Sistemleri',
    categoryId: 17039625,
    typeId: 115948871,
    categoryName: 'Ütüler ve buhar makineleri',
    typeName: 'Buhar jeneratörlü ütü',
    path: ['Ev aletleri', 'Ütüler ve buhar makineleri', 'Buhar jeneratörlü ütü'],
  },
  {
    id: 'utu',
    label: 'Standart Ütü',
    russianLabel: 'Утюг',
    icon: '👔',
    groupId: 'ironing-steam',
    groupName: 'Ütü & Buhar Sistemleri',
    categoryId: 17039625,
    typeId: 91429,
    categoryName: 'Ütüler ve buhar makineleri',
    typeName: 'Ütü',
    path: ['Ev aletleri', 'Ütüler ve buhar makineleri', 'Ütü'],
  },

  // 4. Kişisel Bakım & Güzellik
  {
    id: 'tiras-makinesi',
    label: 'Tıraş Makinesi',
    russianLabel: 'Электробритва',
    icon: '🪒',
    groupId: 'personal-care',
    groupName: 'Kişisel Bakım & Güzellik',
    categoryId: 17039624,
    typeId: 91687,
    categoryName: 'Saç kesme cihazları ve aksesuarları',
    typeName: 'Tıraş makinesi',
    path: ['Ev aletleri', 'Saç kesme cihazları ve aksesuarları', 'Tıraş makinesi'],
  },
  {
    id: 'trimmer',
    label: 'Trimmer',
    russianLabel: 'Триммер',
    icon: '✂️',
    groupId: 'personal-care',
    groupName: 'Kişisel Bakım & Güzellik',
    categoryId: 17039624,
    typeId: 91683,
    categoryName: 'Saç kesme cihazları ve aksesuarları',
    typeName: 'Trimmer',
    path: ['Ev aletleri', 'Saç kesme cihazları ve aksesuarları', 'Trimmer'],
  },
  {
    id: 'lazer-epilasyon-ipl',
    label: 'Lazer Epilasyon Cihazı IPL',
    russianLabel: 'Фотоэпилятор',
    icon: '⚡',
    groupId: 'personal-care',
    groupName: 'Kişisel Bakım & Güzellik',
    categoryId: 77868900,
    typeId: 96767,
    categoryName: 'Epilatörler',
    typeName: 'Lazer epilatör',
    path: ['Kişisel bakım ve hijyen', 'Epilatörler', 'Lazer epilatör'],
  },
  {
    id: 'epilator',
    label: 'Epilatör',
    russianLabel: 'Эпилятор',
    icon: '✨',
    groupId: 'personal-care',
    groupName: 'Kişisel Bakım & Güzellik',
    categoryId: 77868900,
    typeId: 91688,
    categoryName: 'Epilatörler',
    typeName: 'Epilatör',
    path: ['Kişisel bakım ve hijyen', 'Epilatörler', 'Epilatör'],
  },
  {
    id: 'sac-duzlestirici',
    label: 'Saç Düzleştirici',
    russianLabel: 'Выпрямитель волос',
    icon: '💁‍♀️',
    groupId: 'personal-care',
    groupName: 'Kişisel Bakım & Güzellik',
    categoryId: 17039639,
    typeId: 91724,
    categoryName: 'Fön makineleri ve termal fırçalar',
    typeName: 'Saç Düzleştirici',
    path: ['Ev aletleri', 'Fön makineleri ve termal fırçalar', 'Saç Düzleştirici'],
  },
  {
    id: 'sac-kurutma-makinesi',
    label: 'Saç Kurutma Makinesi',
    russianLabel: 'Фен',
    icon: '💨',
    groupId: 'personal-care',
    groupName: 'Kişisel Bakım & Güzellik',
    categoryId: 17039639,
    typeId: 91730,
    categoryName: 'Fön makineleri ve termal fırçalar',
    typeName: 'Saç kurutma makinesi',
    path: ['Ev aletleri', 'Fön makineleri ve termal fırçalar', 'Saç kurutma makinesi'],
  },

  // 5. Sofra & Mutfak Eşyaları (Züccaciye / Kaseler)
  {
    id: 'salata-kasesi',
    label: 'Salata Kasesi',
    russianLabel: 'Салатник',
    icon: '🥗',
    groupId: 'tableware',
    groupName: 'Sofra & Mutfak Eşyaları',
    categoryId: 17028741,
    typeId: 92519,
    categoryName: 'Столовая посуда',
    typeName: 'Salata tabağı',
    path: ['Дом и сад', 'Столовая посуда', 'Салатник'],
  },
  {
    id: 'kase-seti',
    label: 'Mutfak Kasesi / Kase Seti',
    russianLabel: 'Миска',
    icon: '🥣',
    groupId: 'tableware',
    groupName: 'Sofra & Mutfak Eşyaları',
    categoryId: 17028741,
    typeId: 92506,
    categoryName: 'Столовая посуда',
    typeName: 'Kase',
    path: ['Дом и сад', 'Столовая посуда', 'Миска'],
  },

  // 6. Temizlik & Ev Bakımı
  {
    id: 'dikey-supurge',
    label: 'Dikey Süpürge (Şarjlı / Akülü)',
    russianLabel: 'Вертикальный пылесос',
    icon: '🔋',
    groupId: 'cleaning',
    groupName: 'Temizlik & Ev Bakımı',
    categoryId: 17039623,
    typeId: 91587,
    categoryName: 'Elektrikli süpürgeler',
    typeName: 'Dikey Süpürge',
    path: ['Ev aletleri', 'Elektrikli süpürgeler', 'Dikey Süpürge'],
  },
  {
    id: 'robot-supurge',
    label: 'Robot Süpürge',
    russianLabel: 'Робот-пылесос',
    icon: '🧹',
    groupId: 'cleaning',
    groupName: 'Temizlik & Ev Bakımı',
    categoryId: 17039623,
    typeId: 91592,
    categoryName: 'Elektrikli süpürgeler',
    typeName: 'Robot süpürge',
    path: ['Ev aletleri', 'Elektrikli süpürgeler', 'Robot süpürge'],
  },
];


export const PRESET_CATEGORY_GROUPS: PresetCategoryGroup[] = [
  {
    id: 'kitchen-cooking',
    name: 'Mutfak & Pişirme Aletleri',
    icon: '🍳',
    categories: PRESET_CATEGORIES.filter((c) => c.groupId === 'kitchen-cooking'),
  },
  {
    id: 'food-prep',
    name: 'Gıda Hazırlama & Mikserler',
    icon: '🥣',
    categories: PRESET_CATEGORIES.filter((c) => c.groupId === 'food-prep'),
  },
  {
    id: 'ironing-steam',
    name: 'Ütü & Buhar Sistemleri',
    icon: '👔',
    categories: PRESET_CATEGORIES.filter((c) => c.groupId === 'ironing-steam'),
  },
  {
    id: 'personal-care',
    name: 'Kişisel Bakım & Güzellik',
    icon: '🪒',
    categories: PRESET_CATEGORIES.filter((c) => c.groupId === 'personal-care'),
  },
  {
    id: 'tableware',
    name: 'Sofra & Mutfak Eşyaları',
    icon: '🥗',
    categories: PRESET_CATEGORIES.filter((c) => c.groupId === 'tableware'),
  },
  {
    id: 'cleaning',
    name: 'Temizlik & Ev Bakımı',
    icon: '🧹',
    categories: PRESET_CATEGORIES.filter((c) => c.groupId === 'cleaning'),
  },
];
